apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: react-app-esti
  name: react-app-esti
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app-esti
  template:
    metadata:
      labels:
        app: react-app-esti
    spec:
      containers:
      - name: react-app-esti
        image: rochel05/react-app-esti:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
