apiVersion: v1
kind: Service
metadata:
  name: react-app-esti
  labels:
    app: react-app-esti
spec:
  type: NodePort
  ports:
  - port: 3000
    name: http
    nodePort: 30080
  selector:
    app: react-app-esti